[build-system]
requires = [
  "setuptools>=80.9.0",
  "wheel>=0.45.1"
]
build-backend = "setuptools.build_meta"

[project]
name = "backend_placeholder"
version = "1.0.0"
requires-python = ">=3.13"

dependencies = [
  "boto3>=1.34.0",
  "pydantic",
  "fastapi",
  "uvicorn",
  "python-multipart",
  "pytest-asyncio",
]

[tool.setuptools.packages.find]
where = ["lib"]

[project.scripts]
deploy-backend = "backend_placeholder.server:serve"
